from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 652)
        font = QtGui.QFont()
        font.setPointSize(4)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalLayout.addWidget(self.line_14)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(72, 237, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stackedWidget.setFont(font)
        self.TasksPage = QtWidgets.QWidget()
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.TasksPage)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.addFolderbttn = QtWidgets.QPushButton(self.TasksPage)
        self.addFolderbttn.setMinimumSize(QtCore.QSize(150, 0))
        self.addFolderbttn.setCheckable(True)
        self.verticalLayout_3.addWidget(self.addFolderbttn)
        self.scrollArea = QtWidgets.QScrollArea(self.TasksPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.Today = QtWidgets.QPushButton(self.TasksPage)
        self.Today.setFont(font)
        self.Today.setCheckable(True)
        self.verticalLayout_3.addWidget(self.Today)
        self.CompletedTasks = QtWidgets.QPushButton(self.TasksPage)
        self.CompletedTasks.setCheckable(True)
        self.verticalLayout_3.addWidget(self.CompletedTasks)
        self.filter = QtWidgets.QPushButton(self.TasksPage)
        self.filter.setCheckable(True)
        self.verticalLayout_3.addWidget(self.filter)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.TasksPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.SearchBar = QtWidgets.QLineEdit(self.TasksPage)
        self.SearchBar.setFont(font)
        self.horizontalLayout_2.addWidget(self.SearchBar)
        self.searchBttn = QtWidgets.QPushButton(self.TasksPage)
        self.searchBttn.setFont(font)
        self.searchBttn.setCheckable(True)
        self.searchBttn.setChecked(False)
        self.horizontalLayout_2.addWidget(self.searchBttn)
        self.addTasbkttn = QtWidgets.QPushButton(self.TasksPage)
        self.addTasbkttn.setObjectName("addTaskbttn")
        self.addTasbkttn.setFont(font)
        self.horizontalLayout_2.addWidget(self.addTasbkttn)
        self.refreshBttn = QtWidgets.QPushButton(self.TasksPage)
        self.refreshBttn.setObjectName("refreshBttn")
        font.setBold(True)
        font.setWeight(75)
        self.refreshBttn.setFont(font)
        self.horizontalLayout_2.addWidget(self.refreshBttn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.AllTasks_GridLayout = QtWidgets.QGridLayout()
        self.verticalLayout_2.addLayout(self.AllTasks_GridLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.TasksPage)
        
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "All Tasks"))
        self.addFolderbttn.setText(_translate("MainWindow", "Folders"))
        self.Today.setText(_translate("MainWindow", "☀ Today"))
        self.CompletedTasks.setText(_translate("MainWindow", "Completed Tasks"))
        self.filter.setText(_translate("MainWindow", "Filters"))
        self.SearchBar.setPlaceholderText(_translate("MainWindow", "Search"))
        self.searchBttn.setText(_translate("MainWindow", "🔍"))
        self.addTasbkttn.setText(_translate("MainWindow", "+ Add Task"))
        self.refreshBttn.setText(_translate("MainWindow", "⟳"))
